"""`AuditEvent` — one recorded runtime event (§15).

§15.6 names `AuditEvent` as `queryAuditLog`'s return type. It is the only §15
type the frozen specification names, and the **frozen Data Models table has no
row for it** — so its field list comes from §15.4's inputs plus §15.2's stated
responsibilities, and from nothing else.

    §15.4  "Structured event objects (type, project_id, conversation_id,
            payload) from any module."
    §15.2  "Accept structured events from any module; **timestamp** and tag
            with project_id/conversation_id; persist them."

Four fields the caller supplies, two the logger adds. No others were invented.

**`event_id` is generated by the logger, never by the caller.** It has a default
here so a caller can construct the event it wants recorded without inventing an
identity — and whatever it holds at that point is **replaced** when the event is
logged. That is not a courtesy: it is the mechanism by which identity stays the
logger's, and a test pins it.

The consequence is recorded rather than papered over: because callers cannot
supply an id, **§15.12(d)'s duplicate-id scenario cannot arise from outside**,
and no artificial duplicate detection was written to make it look otherwise.
See OB-2 in `docs/known-issues-runtime.md`.

`timestamp` follows the repository's existing convention — an ISO-8601 UTC
string, as `SessionState.created_at` and `ConversationContext.started_at`
already use.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field
from types import MappingProxyType


@dataclass(frozen=True, slots=True)
class AuditEvent:
    """One auditable event. Immutable once written (§15.10).

    Frozen with `slots`, and `payload` is wrapped in a `MappingProxyType`, so a
    retrieved event cannot be edited by whoever retrieved it — which is what
    §15.10 actually requires of a record that has already been stored.
    """

    type: str
    project_id: str
    conversation_id: str
    payload: Mapping[str, str] = field(default_factory=dict)
    #: Assigned by the Audit Logger. Anything a caller places here is replaced.
    event_id: str = ""
    #: Assigned by the Audit Logger, in the repository's ISO-8601 UTC form.
    timestamp: str | None = None

    def __post_init__(self) -> None:
        object.__setattr__(self, "payload", MappingProxyType(dict(self.payload)))

    @property
    def is_recorded(self) -> bool:
        """Whether this event carries the identity and time a logger assigns."""
        return bool(self.event_id) and self.timestamp is not None


@dataclass(frozen=True, slots=True)
class AuditFilters:
    """What `queryAuditLog` may narrow by (§15.6).

    Exactly three fields, and deliberately not one more. §15.6 says only
    `queryAuditLog(filters)`; the word "filters" appears nowhere else in the
    specification or the repository, so the authorized set is the three values
    an event is actually tagged with.

    Every field is optional; supplying several **ANDs** them. There is no
    ordering field — results come back in insertion order — no pagination, no
    retention window and no authorization scope. Those semantics are undefined
    by §15 and none was invented.
    """

    type: str | None = None
    project_id: str | None = None
    conversation_id: str | None = None

    @property
    def is_empty(self) -> bool:
        """True when nothing is narrowed, so every event matches."""
        return (
            self.type is None
            and self.project_id is None
            and self.conversation_id is None
        )

    def matches(self, event: AuditEvent) -> bool:
        """Whether one event satisfies every supplied filter.

        Conjunctive by ruling. An absent filter constrains nothing; it does not
        mean "match the empty string".
        """
        if self.type is not None and event.type != self.type:
            return False
        if self.project_id is not None and event.project_id != self.project_id:
            return False
        return not (
            self.conversation_id is not None
            and event.conversation_id != self.conversation_id
        )
