"""A durable `AuditLogStore` over SQLite — the OB-1 adapter.

§15.8 names the external dependency: *"A durable, ideally append-only log
store."* `InMemoryAuditLogStore` satisfies append-only and loses everything when
the process ends, which is what **OB-1** recorded. This module is the concrete
durable implementation of the same seam.

**It is an adapter, not a default.** `runtime/observability/__init__.py` and
`adapters/__init__.py` import nothing from here; the **composition root** does,
explicitly, and is the only importer —
`test_only_the_composition_root_imports_the_adapter` pins that. `activate()`
constructs this store over `ORBITLANCE_AUDIT_DB`, so **production audit
persistence is durable** (**OB-1** closed 2026-09-01, **RE-4** closed
2026-09-01).

Choosing where audit records live stays the composition root's decision. An
adapter is selected by explicit import and explicit construction, and the
existence of one activates it for nothing.

---

## What "durable" means here, and only here

Minimally, and by ruling: **an appended event survives destruction of this store
object and is readable by a newly constructed store over the same database
path.** That is the whole claim. In particular this module does **not** claim:

* **multi-process safety** — two processes appending to one database file is out
  of scope, and no locking, threading or coordination exists here to make it
  safe. RE-3's single-threaded posture is unchanged and ADR 0003's V-7 deadline
  is not triggered;
* **thread safety** — none is claimed; a `sqlite3` connection is not shared
  across operations, let alone across threads;
* **retention** — records are kept **indefinitely**. No policy exists anywhere in
  this repository to implement, so nothing here expires, compacts or evicts. The
  database grows without bound until something outside the framework removes it;
* **access control** — whatever the host filesystem gives the database file, and
  nothing more. No application-level authorization is invented.

## Structural notes

**No `AuditLogStore` import.** The contract is a structural Protocol, so
satisfying it requires inheriting nothing. Importing `runtime.observability`
would add an edge this adapter does not need; it depends on `runtime.models`
alone, which makes an import cycle impossible by construction rather than by
care.

**One connection per operation** — open, act, commit where a write happened,
close. The public contract has two members and no `close()`, so a long-lived
handle would be a resource nothing could release. Per-operation connections cost
performance and buy a store whose destruction means exactly nothing, which is
what the durability definition above rests on.

**No duplicate detection, and deliberately no `UNIQUE` on `event_id`.** Ids are
generated by the logger and callers cannot supply one, so a collision cannot
arise from outside — **OB-2** records that, and a unique index here would be a
check that can never fire, which is worse than an honest absence. Two identical
events are two rows, as the committed §15 behaviour requires.
"""

from __future__ import annotations

import json
import sqlite3
from collections.abc import Callable
from pathlib import Path
from typing import Any

from runtime.models.audit import AuditEvent, AuditFilters

#: The table this adapter owns. Explicitly named so nothing collides with a
#: database a deployment may already be using for something else.
TABLE = "audit_events"

#: `seq` is a storage-level ordering key aliasing SQLite's rowid. It makes
#: insertion order explicit rather than implicit, and it **never surfaces in
#: `AuditEvent`** — the model's field list is frozen at six.
_SCHEMA = f"""
CREATE TABLE IF NOT EXISTS {TABLE} (
    seq             INTEGER PRIMARY KEY,
    event_id        TEXT NOT NULL,
    type            TEXT NOT NULL,
    project_id      TEXT NOT NULL,
    conversation_id TEXT NOT NULL,
    timestamp       TEXT,
    payload         TEXT NOT NULL
)
"""

_INSERT = f"""
INSERT INTO {TABLE}
    (event_id, type, project_id, conversation_id, timestamp, payload)
VALUES (?, ?, ?, ?, ?, ?)
"""

_SELECT = f"""
SELECT event_id, type, project_id, conversation_id, timestamp, payload
FROM {TABLE}
ORDER BY seq
"""


class SqliteAuditLogStoreError(Exception):
    """This adapter could not read or write its database.

    Every `sqlite3` failure and every malformed stored record is normalised to
    this type, so no backing-store detail crosses the seam — the same discipline
    §9.9 applies to provider errors.

    **A corrupt record raises; it is never silently skipped.** Dropping an
    unreadable row would make an audit log quietly incomplete, which is the
    failure mode an audit log exists to prevent. No recovery or repair semantics
    are invented here.

    Raising is correct on the write path too: §15.9 requires that a store
    failure not block the *conversation*, and the Runtime Engine's guard is what
    honours that. This exception reaching a caller is how a problem becomes
    visible at all.
    """


class SqliteAuditLogStore:
    """Append-only audit storage in a SQLite database. Satisfies `AuditLogStore`.

    The database path is supplied explicitly at construction. There is no
    environment variable, settings object, configuration file or default
    location — a store writes where its caller said, and nowhere else.
    """

    __slots__ = ("_path",)

    def __init__(self, database_path: str | Path) -> None:
        """Open (or create) the database and ensure the table exists.

        Construction touches the filesystem: it creates the file if absent and
        runs `CREATE TABLE IF NOT EXISTS`. Two stores given the same path share
        one database — that is what makes durability observable across store
        objects, and it is also why physical storage being shared says nothing
        about project isolation. Isolation here is a property of the query
        filters, not of the file.
        """
        self._path = Path(database_path)
        self._run(lambda connection: connection.execute(_SCHEMA),
                  f"could not open or initialise the audit database at {self._path}")

    @property
    def database_path(self) -> Path:
        """Where this store keeps its records."""
        return self._path

    # -- AuditLogStore --------------------------------------------------------
    def append(self, event: AuditEvent) -> None:
        """Insert one event. Nothing in this method can touch an existing row.

        The statement is an `INSERT` with no `ON CONFLICT` clause and no `UPDATE`
        anywhere in this module, so §15.10's "immutable once written" is a
        property of the code rather than a promise about it.
        """
        payload = json.dumps(dict(event.payload), sort_keys=True)
        row = (
            event.event_id,
            event.type,
            event.project_id,
            event.conversation_id,
            event.timestamp,
            payload,
        )
        self._run(
            lambda connection: connection.execute(_INSERT, row),
            f"could not append an audit event to {self._path}",
        )

    def query(self, filters: AuditFilters) -> tuple[AuditEvent, ...]:
        """Every stored event matching `filters`, oldest first.

        Ordered by `seq`, which is insertion order — not by timestamp, since two
        events can share one. Filtering is done in Python by
        `AuditFilters.matches`, so the AND semantics live in exactly one place
        and cannot drift between the in-memory store and this one.

        Raises `SqliteAuditLogStoreError` if the database cannot be read or a
        stored record cannot be reconstructed.
        """
        rows = self._run(
            lambda connection: connection.execute(_SELECT).fetchall(),
            f"could not read audit events from {self._path}",
        )
        events = tuple(self._event_from(row) for row in rows)
        return tuple(event for event in events if filters.matches(event))

    def __len__(self) -> int:
        """How many events are stored, ignoring every filter."""
        counted = self._run(
            lambda connection: connection.execute(
                f"SELECT COUNT(*) FROM {TABLE}"  # noqa: S608 - a fixed table name
            ).fetchone(),
            f"could not count audit events in {self._path}",
        )
        return int(counted[0])

    # -- internals ------------------------------------------------------------
    def _run(self, operation: Callable[[sqlite3.Connection], Any], failure: str) -> Any:
        """Open a connection, run one operation, commit, close.

        `with connection` commits on success and rolls back on an exception;
        the `finally` closes. Nothing holds a handle between calls, so
        destroying this object releases nothing and loses nothing — which is
        what makes the durability claim in this module's docstring true.

        Every `sqlite3` failure becomes `SqliteAuditLogStoreError`, so no
        backing-store type crosses the seam.
        """
        try:
            connection = sqlite3.connect(self._path)
        except sqlite3.Error as error:
            raise SqliteAuditLogStoreError(f"{failure}: {error}") from error
        try:
            with connection:
                return operation(connection)
        except sqlite3.Error as error:
            raise SqliteAuditLogStoreError(f"{failure}: {error}") from error
        finally:
            connection.close()

    @staticmethod
    def _event_from(row: tuple[str, str, str, str, str | None, str]) -> AuditEvent:
        """Rebuild one `AuditEvent` from a stored row.

        A record that will not decode, or that does not hold the
        `Mapping[str, str]` payload the model declares, raises. It is not
        skipped: an audit log that quietly omits what it cannot read is worse
        than one that says it is broken.
        """
        event_id, type_, project_id, conversation_id, timestamp, payload = row
        try:
            decoded = json.loads(payload)
        except (TypeError, ValueError) as error:
            raise SqliteAuditLogStoreError(
                f"audit event {event_id!r} has an unreadable payload"
            ) from error

        if not isinstance(decoded, dict) or not all(
            isinstance(key, str) and isinstance(value, str)
            for key, value in decoded.items()
        ):
            raise SqliteAuditLogStoreError(
                f"audit event {event_id!r} has a payload that is not a "
                "mapping of strings to strings"
            )

        return AuditEvent(
            type=type_,
            project_id=project_id,
            conversation_id=conversation_id,
            payload=decoded,
            event_id=event_id,
            timestamp=timestamp,
        )
